#ifndef GE_ACH_DEF_H
#define GE_ACH_DEF_H

enum GEAchievements
{
	FIRST_GES_ACH = 150,

	// Beta 3 Achievements
	ACHIEVEMENT_GES_LICENSE_TO_KILL = 150,
	ACHIEVEMENT_GES_ONE_WITH_BULLET,
	ACHIEVEMENT_GES_INVINCIBLE,
	ACHIEVEMENT_GES_SILENT_ASSASSIN,
	ACHIEVEMENT_GES_SHARPSHOOTAH,
	ACHIEVEMENT_GES_UFOD,
	ACHIEVEMENT_GES_OCTOPUSSY,
	
	ACHIEVEMENT_GES_PP7_LEVEL1,
	ACHIEVEMENT_GES_PP7_LEVEL2,
	ACHIEVEMENT_GES_PP7_LEVEL3,

	ACHIEVEMENT_GES_KLOBB_LEVEL1,
	ACHIEVEMENT_GES_KLOBB_LEVEL2,
	ACHIEVEMENT_GES_KLOBB_LEVEL3,

	ACHIEVEMENT_GES_PHANTOM_LEVEL1,
	ACHIEVEMENT_GES_PHANTOM_LEVEL2,
	ACHIEVEMENT_GES_PHANTOM_LEVEL3,

	ACHIEVEMENT_GES_RCP90_LEVEL1,
	ACHIEVEMENT_GES_RCP90_LEVEL2,
	ACHIEVEMENT_GES_RCP90_LEVEL3,

	ACHIEVEMENT_GES_AR33_LEVEL1,
	ACHIEVEMENT_GES_AR33_LEVEL2,
	ACHIEVEMENT_GES_AR33_LEVEL3,

	ACHIEVEMENT_GES_SNIPERRIFLE_LEVEL1,
	ACHIEVEMENT_GES_SNIPERRIFLE_LEVEL2,
	ACHIEVEMENT_GES_SNIPERRIFLE_LEVEL3,

	ACHIEVEMENT_GES_REMOTEMINE_LEVEL1,
	ACHIEVEMENT_GES_REMOTEMINE_LEVEL2,
	ACHIEVEMENT_GES_REMOTEMINE_LEVEL3,

	ACHIEVEMENT_GES_PROXIMITYMINE_LEVEL1,
	ACHIEVEMENT_GES_PROXIMITYMINE_LEVEL2,
	ACHIEVEMENT_GES_PROXIMITYMINE_LEVEL3,

	ACHIEVEMENT_GES_TIMEDMINE_LEVEL1,
	ACHIEVEMENT_GES_TIMEDMINE_LEVEL2,
	ACHIEVEMENT_GES_TIMEDMINE_LEVEL3,

	ACHIEVEMENT_GES_FORENGLAND,
	ACHIEVEMENT_GES_DUTCHRUDDER,
	ACHIEVEMENT_GES_GOLDFINGERED,

	// BETA 3.1 ACHIEVEMENTS
	ACHIEVEMENT_GES_WHO_THROWS_SHOE,
	ACHIEVEMENT_GES_JAMESBOND,
	ACHIEVEMENT_GES_HAYDAYMAYDAY,
	ACHIEVEMENT_GES_MISCHMISHKIN,
	ACHIEVEMENT_GES_TWO_FACED,
	ACHIEVEMENT_GES_WHY_WONT_YOU_DIE,
	ACHIEVEMENT_GES_VIASHINOWNED,
	ACHIEVEMENT_GES_WORLD_IS_NOT_ENOUGH,
	ACHIEVEMENT_GES_SECRET_AGENT_MAN,
	ACHIEVEMENT_GES_GOLDENEYE_MASTER,

	ACHIEVEMENT_GES_BE_HONORED,
	ACHIEVEMENT_GES_BE_GRATEFUL,
	ACHIEVEMENT_GES_DIE_ANOTHER_DAY,
	
	// BETA 4 ACHIEVEMENTS
	ACHIEVEMENT_GES_BOOM_HEADSHOT,
	ACHIEVEMENT_GES_LATE_ATTENDANCE,
	ACHIEVEMENT_GES_SHAKEN_LEVEL1,
	ACHIEVEMENT_GES_SHAKEN_LEVEL2,
	ACHIEVEMENT_GES_SHAKEN_LEVEL3,
	ACHIEVEMENT_GES_SCARAMANGAS_PRIDE,
	ACHIEVEMENT_GES_MAN_WHO_CANT_DIE,
	ACHIEVEMENT_GES_RUSSIAN_ROULETTE,
	ACHIEVEMENT_GES_THE_SPECIALIST,
	ACHIEVEMENT_GES_004,
	ACHIEVEMENT_GES_FOR_ENGLAND_ALEC,
	ACHIEVEMENT_GES_THROUGH_FIRE_FLAMES,
	ACHIEVEMENT_GES_DOMINO_EFFECT,
	ACHIEVEMENT_GES_LTG_LEVEL1,
	ACHIEVEMENT_GES_LTG_LEVEL2,
	ACHIEVEMENT_GES_LTG_LEVEL3,
	ACHIEVEMENT_GES_MOONRAKER_LEVEL1,
	ACHIEVEMENT_GES_MOONRAKER_LEVEL2,
	ACHIEVEMENT_GES_MOONRAKER_LEVEL3,
	ACHIEVEMENT_GES_KF7_LEVEL1,
	ACHIEVEMENT_GES_KF7_LEVEL2,
	ACHIEVEMENT_GES_KF7_LEVEL3,
	ACHIEVEMENT_GES_LAST_AGENT_STANDING,
	ACHIEVEMENT_GES_YOU_CANT_WIN,
	ACHIEVEMENT_GES_FLESH_WOUND,
	ACHIEVEMENT_GES_MAKE_MY_MAYDAY,
	ACHIEVEMENT_GES_THATS_MY_OCTOPUSSY,
	ACHIEVEMENT_GES_TWO_KLOBBS,
	ACHIEVEMENT_GES_BREAK_A_LEG,
	ACHIEVEMENT_GES_TARGET_PRACTICE,

	MAX_GES_ACH,
};

#endif